config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]

  resources :bands do
      member do
        resources :albums, only: [:new]
      end
    end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    member do
      resources :tracks, only: [:new]
    end
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]

  root to: "bands#index"
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, :band_id, presence: true

  belongs_to :band
  has_many :tracks,
    dependent: :destroy

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    dependent: :destroy
  has_many :tracks, through: :albums
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :title, :album_id, :lyrics, presence: true

  belongs_to :album
  has_one :band, through: :album
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: {minimum: 6}, allow_nil: true

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    user && user.is_password?(password) ? user : nil
  end

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end


  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(32)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save
    self.session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter do
    redirect_to new_session_url unless current_user
  end

  def new
    @bands = Band.all
    @album = Album.new(band_id: params[:id])
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @bands = Band.all
    @album = Album.find_by_id(params[:id])
  end

  def show
    @album = Album.includes(:tracks, :band).find_by_id(params[:id])
  end

  def update
    @album = Album.find_by_id(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.includes(:band).find_by_id(params[:id])

    if @album.destroy
      redirect_to band_url(@album.band)
    else
      flash.now[:errors] = ["Album cannot be deleted."]
      render :show
    end
  end

  private

  def album_params
    params.require(:album).permit(:title, :band_id, :live)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login_user!(user)
    user.reset_session_token!
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_filter do
    redirect_to new_session_url unless current_user
  end

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find_by_id(params[:id])
  end

  def update
    @band = Band.find_by_id(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def show
    @band = Band.find_by_id(params[:id])
    @albums = @band.albums
  end

  def destroy
    @band = Band.find_by_id(params[:id])

    if @band.destroy
      redirect_to bands_url
    else
      flash.now[:errors] = ["Band could not be destroyed"]
      render :show
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = login_params[:email]
    password = login_params[:password]

    @user = User.find_by_credentials(email, password)

    if @user
      login_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid username or password." ]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to root_url
  end

  private

  def login_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter do
    redirect_to new_session_url unless current_user
  end

  def new
    @track = Track.new(album_id: params[:id])
    @album = Album.find_by_id(params[:id])
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end

  end

  def edit
    #allow user to change album of track?
    @track = Track.find_by_id(params[:id])
  end

  def show
    @track = Track.includes(:album, :band).find_by_id(params[:id])
  end

  def update
    @track = Track.find_by_id(params[:id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end

  end

  def destroy
    @track = Track.find_by_id(params[:id])

    if @track.destroy
      redirect_to tracks_url
    else
      flash.now[:errors] = ["Track is invincible and could not be deleted."]
      render :show
    end

  end

  def track_params
    params.require(:track).permit(:title, :album_id, :bonus, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :session_token)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type=hidden name=authenticity_token value=#{form_authenticity_token}>".html_safe
  end

end

app/helpers/bands_helper.rb
module BandsHelper

  def render_album_title(album)
    "#{album.title} #{"(LIVE)" if album.live}"
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<form action=<%= action %> method="POST" >
  <%= auth_token %>

  <input type="hidden" name="_method" value=<%= method %> />

  <label> Title:
    <input
      type="text"
      name="album[title]"
      id="album_title"
      value="<%= @album.title %>">
  </label>

  <label> Band:
    <select name="album[band_id]">
      <% @bands.each do |band| %>
        <option value=<%= band.id %>
                id="band_name_<%= band.name.underscore %>"
                <%= " selected" if @album.band_id == band.id %>>
          <%=band.name%>
        </option>
      <% end %>
    </select>

    <label> Live
      <input type="radio" name="album[live]" id="album_live_true" value=true
        <%= " checked" if @album.live %> />
    </label>
    <label> Studio
      <input type="radio" name="album[live]" id="album_live_false" value=false
        <%= " checked" unless @album.live %> />
    </label>

    <input type="submit" value="Submit album">
  </form>

app/views/albums/edit.html.erb
<h1> Edit an album </h1>
<%= render "form", action: album_url(@album), method: "patch" %>

app/views/albums/new.html.erb
<h1> New album </h1>
<%= render "form", action: albums_url, method: "post" %>

app/views/albums/show.html.erb
<h1> <%=@album.band.name %> - <%= @album.title %> <%="#{"(LIVE)" if @album.live}" %> </h1>
<h2> Track list: </h2>
  <ol>
    <% @album.tracks.each do |track| %>
      <li> <%= link_to track.title, track_url(track) %> </li>
    <% end %>
  </ol>
<%= link_to "Add track", new_track_url(@album) %>  |
<%= link_to "Edit this album", edit_album_url(@album) %>  |
<%= link_to "More albums by #{@album.band.name}", band_url(@album.band) %>
<%= button_to "Delete", album_url(@album), method: "delete" %>

app/views/bands/_form.html.erb
<form action=<%= action %> method="POST" >
  <%= auth_token %>
  <input type="hidden" name="_method" value=<%= method %>
  <label> Band name:
    <input type="text" name="band[name]" id="band_name" value="<%= @band.name %>" >
  </label>
  <input type="submit" value="Submit">
</form>

app/views/bands/edit.html.erb
<h1> Edit a band </h1>
<%= render "form", action: band_url(@band), method: "patch" %>

app/views/bands/index.html.erb
<h1> All bands </h1>
<ul>
  <% @bands.each do |band| %>
    <li> <%= link_to band.name, band_url(band) %> </li>
  <% end %>
</ul>
<%= link_to "Add a band", new_band_url %>

app/views/bands/new.html.erb
<h1> Add a band </h1>
<%= render "form", action: bands_url, method: "create" %>

app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>
<h2> Albums: </h2>
  <ul>
    <% @albums.each do |album| %>
      <li> <%= link_to render_album_title(album), album_url(album) %> </li>
    <% end %>
  </ul>
<%= link_to "Add album", new_album_url %>  |
<%= link_to "Edit band", edit_band_url(@band)%>  |
<%= link_to "More bands", bands_url %>


<%= button_to "Remove band", band_url(@band), method: "delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <% if current_user %>
    <%= button_to "Sign out", session_url, method: "delete" %>
  <% else %>
    <%= button_to "Log in", new_session_url, method: "get" %><%=
        button_to "Sign up", new_user_url, method: "get" %>
  <% end %>

</nav>

<%= render "shared/errors" %>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <h3> Looks like some errors have occurred... </h3>
  <ul>
    <% flash[:errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>

app/views/tracks/_form.html.erb
<form action=<%= action %> method="POST" >
  <%= auth_token %>

  <input type="hidden" name="_method" value=<%= method %> />
  <input type="hidden" name="track[album_id]" value=<%=@track.album_id %>

  <label> Title:
    <input
      type="text"
      name="track[title]"
      id="track_title"
      value="<%= @track.title %>">
  </label><br/>

  <label> Bonus track: Y
    <input type="radio" name="track[bonus]" id="track_bonus_true" value=true
      <%= " checked" if @track.bonus %> />
  </label>
  <label> N
    <input type="radio" name="track[bonus]" id="track_bonus_false" value=false
      <%= " checked" unless @track.bonus %> />
  </label><br/>

  <label> Lyrics:<br/>
    <textarea name="track[lyrics]"><%= @track.lyrics %></textarea>
  </label>

  <input type="submit" value="Submit track">
  </form>

app/views/tracks/edit.html.erb
<h1> Edit a track </h1>
<%= render "form", action: track_url(@track), method: "patch" %>

app/views/tracks/new.html.erb
<h1> New track </h1>
<%= render "form", action: tracks_url, method: "post" %>

app/views/tracks/show.html.erb
<h1> <%= @track.title %> by <%= link_to @track.band.name, band_url(@track.band) %> </h1>
<h2> Album: <%= link_to @track.album.title, album_url(@track.album) %> </h2>

<h3> Lyrics: </h3>
<pre><%= @track.lyrics %></pre>

<%= link_to "Edit track", edit_track_url(@track)%>
<%= button_to "Remove track", track_url(@track), method: "delete" %>

app/views/users/new.html.erb
<h1> Sign up </h1>
<form action=<%= users_url %> method="POST">
  <%= auth_token %>
  <label> Email:
    <input type=text name=user[email] />
  </label>
  <label> Password:
    <input type=password name=user[password] />
  </label>
  <input type="submit" value="Sign up" />
</form>

app/views/users/show.html.erb
<%= @user.email %>